### ISSUE TITLE
wallet.balance() endpoint not working

### ISSUE THREAD

**Issue by peterVG** [pygate/pygate-gRPC#27]
See https://github.com/pygate/pygate-gRPC/blob/d64bc68ec61f7bb2a96d5afa7053a708e61d3e73/examples/ffs_wallets.py#L21 it produces the error:  
  `Traceback (most recent call last):  
  File "examples/ffs_wallets.py", line 21, in <module>  
    balance = client.wallet.balance(wallet)  
  File "/Users/peter/Development/pygate-gRPC/venv/lib/python3.7/site-packages/pygate_grpc/wallet.py", line 28, in balance
    return self.client.Balance(req)  
  File "/Users/peter/Development/pygate-gRPC/venv/lib/python3.7/site-packages/grpc/_channel.py", line 826, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Users/peter/Development/pygate-gRPC/venv/lib/python3.7/site-packages/grpc/_channel.py", line 729, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNIMPLEMENTED
	details = "unknown method Balance for service wallet.rpc.RPCService"
	debug_error_string = "{"created":"@1596139208.482368000","description":"Error received from peer ipv4:127.0.0.1:5002","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"unknown method Balance for service wallet.rpc.RPCService","grpc_status":12}"`

N.B. The `balance.list()` endpoint is working correctly as demonstrated by line 7 in the same script.

**Comment by peterVG** [comment]
Fixed in PR https://github.com/pygate/pygate-gRPC/pull/28
